// Questions aligned to Australian Curriculum (AC9)
// Format: { q: question, o: [A,B,C,D], a: correct_index(0-3), l: level(1-3) }

const QUESTIONS = {

  maths_f2: [
    // Level 1 — Foundation: counting, shapes, addition to 10
    {q:"How many stars? ⭐⭐⭐⭐⭐", o:["3","4","5","6"], a:2, l:1},
    {q:"What comes next? 1, 2, 3, ___", o:["5","2","4","6"], a:2, l:1},
    {q:"Which shape has 3 sides?", o:["Circle","Square","Triangle","Rectangle"], a:2, l:1},
    {q:"2 + 3 = ?", o:["4","6","5","7"], a:2, l:1},
    {q:"I have 5 lollies and eat 2. How many are left?", o:["2","3","7","4"], a:1, l:1},
    {q:"Which is the BIGGEST number?", o:["3","7","5","1"], a:1, l:1},
    {q:"A square has ___ sides.", o:["3","5","4","6"], a:2, l:1},
    {q:"4 + 4 = ?", o:["6","9","8","7"], a:2, l:1},
    {q:"How many wheels does a bike have?", o:["3","4","2","1"], a:2, l:1},
    // Level 2 — Year 1: addition to 20, subtraction, place value
    {q:"7 + 5 = ?", o:["11","13","12","10"], a:2, l:2},
    {q:"10 - 4 = ?", o:["5","7","6","4"], a:2, l:2},
    {q:"Which number is between 15 and 20?", o:["12","22","17","13"], a:2, l:2},
    {q:"How many TENS are in 24?", o:["4","2","24","42"], a:1, l:2},
    {q:"Half of 8 is?", o:["2","6","3","4"], a:3, l:2},
    {q:"3 + ___ = 10", o:["8","6","7","5"], a:2, l:2},
    {q:"What shape is a basketball?", o:["Square","Triangle","Cylinder","Sphere"], a:3, l:2},
    {q:"9 + 6 = ?", o:["14","16","15","13"], a:2, l:2},
    {q:"Which is worth MORE? 1 ten-cent coin or 2 five-cent coins?", o:["The 10c","The 2×5c","They are equal","Can't tell"], a:2, l:2},
    // Level 3 — Year 2: addition/subtraction to 30, patterns, simple money
    {q:"15 + 8 = ?", o:["21","22","23","24"], a:2, l:3},
    {q:"20 - 7 = ?", o:["12","14","13","11"], a:2, l:3},
    {q:"3 tens and 5 ones = ?", o:["53","35","305","350"], a:1, l:3},
    {q:"Double 9 is?", o:["18","16","19","17"], a:0, l:3},
    {q:"How many days are in a week?", o:["6","8","7","5"], a:2, l:3},
    {q:"4 + 4 + 4 = ?", o:["8","12","16","14"], a:1, l:3},
    {q:"How many 5c coins make 20c?", o:["2","3","4","5"], a:2, l:3},
    {q:"What is 6 + 7?", o:["12","14","13","15"], a:2, l:3},
    {q:"30 - 14 = ?", o:["14","17","16","15"], a:2, l:3},
  ],

  maths_34: [
    // Level 1 — × by 2,5,10; basic fractions; rounding to 10
    {q:"6 × 4 = ?", o:["20","24","28","22"], a:1, l:1},
    {q:"35 ÷ 5 = ?", o:["6","8","7","9"], a:2, l:1},
    {q:"1 slice from 4 equal pizza slices = ?", o:["¼","½","⅓","¾"], a:0, l:1},
    {q:"Round 47 to the nearest ten.", o:["40","50","45","47"], a:1, l:1},
    {q:"3 × 10 = ?", o:["13","103","30","31"], a:2, l:1},
    {q:"Which fraction is a HALF?", o:["¼","½","⅓","¾"], a:1, l:1},
    {q:"What is 400 + 30 + 6?", o:["4036","4306","436","4360"], a:2, l:1},
    {q:"5 × 5 = ?", o:["10","20","25","30"], a:2, l:1},
    {q:"Half of 20 is?", o:["5","15","10","8"], a:2, l:1},
    // Level 2 — ×÷ 3,4,6,8; fractions ¼ ¾; area counting squares
    {q:"7 × 8 = ?", o:["54","56","63","48"], a:1, l:2},
    {q:"48 ÷ 6 = ?", o:["7","9","8","6"], a:2, l:2},
    {q:"Half of 24 = ?", o:["10","14","12","11"], a:2, l:2},
    {q:"In 4,521 — which digit is in the HUNDREDS place?", o:["4","5","2","1"], a:1, l:2},
    {q:"A rectangle is 6cm × 3cm. What is the AREA?", o:["9 cm²","18 cm²","12 cm²","15 cm²"], a:1, l:2},
    {q:"Which is GREATER: ¾ or ½?", o:["½","¾","They are equal","Can't tell"], a:1, l:2},
    {q:"4 × 9 = ?", o:["32","36","40","42"], a:1, l:2},
    {q:"The perimeter of a square with side 5 cm is?", o:["10 cm","20 cm","25 cm","15 cm"], a:1, l:2},
    {q:"1/4 of 40 = ?", o:["8","20","10","4"], a:2, l:2},
    // Level 3 — ×÷ 7,9,12; fraction comparisons; 4-digit addition
    {q:"9 × 7 = ?", o:["54","56","63","72"], a:2, l:3},
    {q:"12 × 12 = ?", o:["134","144","124","140"], a:1, l:3},
    {q:"Which is LARGEST? ½, ¼, ¾, ⅓", o:["½","¼","¾","⅓"], a:2, l:3},
    {q:"2,345 + 1,678 = ?", o:["4,023","3,923","4,123","4,013"], a:0, l:3},
    {q:"A bag has 5 red and 3 blue balls. What FRACTION are red?", o:["⅝","⅜","3/5","5/3"], a:0, l:3},
    {q:"6,000 - 1,250 = ?", o:["4,850","4,750","5,750","4,650"], a:1, l:3},
    {q:"8 × 8 = ?", o:["56","60","64","72"], a:2, l:3},
    {q:"Round 4,782 to the nearest HUNDRED.", o:["4,700","4,800","4,900","4,780"], a:1, l:3},
    {q:"What is 1/3 of 99?", o:["30","23","33","39"], a:2, l:3},
  ],

  maths_56: [
    // Level 1 — percentages 10%/25%/50%, decimal +/-, fractions to decimals
    {q:"25% of 80 = ?", o:["20","25","40","16"], a:0, l:1},
    {q:"0.3 + 0.7 = ?", o:["0.10","10","1.0","0.37"], a:2, l:1},
    {q:"½ + ¼ = ?", o:["¾","2/6","1/6","½"], a:0, l:1},
    {q:"Which number is PRIME?", o:["9","15","11","21"], a:2, l:1},
    {q:"Area of rectangle 8 cm × 5 cm = ?", o:["26 cm²","40 cm²","13 cm²","45 cm²"], a:1, l:1},
    {q:"3² = ?", o:["6","9","8","12"], a:1, l:1},
    {q:"5.4 − 2.8 = ?", o:["2.6","3.6","2.4","3.4"], a:0, l:1},
    {q:"10% of 350 = ?", o:["35","3.5","350","3500"], a:0, l:1},
    {q:"½ as a decimal = ?", o:["0.2","0.25","0.5","5.0"], a:2, l:1},
    // Level 2 — %, fraction × fraction, order of operations, volume
    {q:"15% of 200 = ?", o:["25","30","20","35"], a:1, l:2},
    {q:"Simplify 12/16.", o:["3/4","6/8","2/3","4/5"], a:0, l:2},
    {q:"2 + 3 × 4 = ? (order of operations)", o:["20","14","24","18"], a:1, l:2},
    {q:"Volume of box 4cm × 3cm × 2cm = ?", o:["24 cm³","18 cm³","9 cm³","20 cm³"], a:0, l:2},
    {q:"¾ as a decimal = ?", o:["0.75","0.34","0.43","3.4"], a:0, l:2},
    {q:"Mean of 4, 6, 8, 10 = ?", o:["6","7","8","9"], a:1, l:2},
    {q:"2.5 × 4 = ?", o:["8.0","10.0","12.0","6.0"], a:1, l:2},
    {q:"50% of 64 = ?", o:["16","32","8","64"], a:1, l:2},
    {q:"What is -3 + 7?", o:["10","-4","4","-10"], a:2, l:2},
    // Level 3 — harder %, squares/cubes, mean/median, negative numbers
    {q:"40% of 150 = ?", o:["50","60","70","45"], a:1, l:3},
    {q:"2³ + 3² = ?", o:["13","17","11","15"], a:1, l:3},
    {q:"Which is the LARGEST? 3/5, 0.65, 62%, 5/8", o:["3/5","0.65","62%","5/8"], a:1, l:3},
    {q:"A triangle has angles 60° and 80°. Third angle = ?", o:["40°","60°","50°","30°"], a:0, l:3},
    {q:"3/4 × 2/3 = ?", o:["5/7","6/7","1/2","8/9"], a:2, l:3},
    {q:"1,250 ÷ 25 = ?", o:["40","50","45","55"], a:1, l:3},
    {q:"Median of 3, 7, 9, 11, 15 = ?", o:["7","9","11","3"], a:1, l:3},
    {q:"-8 + 3 = ?", o:["-11","-5","5","11"], a:1, l:3},
    {q:"What is 20% of 85?", o:["15","17","19","21"], a:1, l:3},
  ],

  english_f2: [
    // Level 1 — initial sounds, rhyme, sight words
    {q:"Which word starts with the sound 'B'?", o:["Dog","Ball","Cat","Sun"], a:1, l:1},
    {q:"Which word RHYMES with 'cat'?", o:["Dog","Car","Hat","Cup"], a:2, l:1},
    {q:"Which word starts with the same sound as 'fish'?", o:["Bag","Flower","Dog","Sun"], a:1, l:1},
    {q:"How many WORDS are in this sentence? 'I like dogs.'", o:["2","4","3","5"], a:2, l:1},
    {q:"Which word RHYMES with 'ball'?", o:["Bell","Tall","Fill","Pull"], a:1, l:1},
    {q:"Which word starts with the sound 'S'?", o:["Train","Peach","Star","Rain"], a:2, l:1},
    {q:"'Big' and 'large' mean the ___", o:["opposite","same","nothing","sound"], a:1, l:1},
    {q:"Which word rhymes with 'cake'?", o:["Back","Make","Book","Kick"], a:1, l:1},
    {q:"Which picture word starts with 'ch'? (ch-ch-...)", o:["Ship","Chip","Thin","Sing"], a:1, l:1},
    // Level 2 — blends, plurals, capitals
    {q:"'Dog' becomes 'dogs'. What do we add to make most words PLURAL?", o:["ed","er","s","ing"], a:2, l:2},
    {q:"Which word has the blend 'st' at the start?", o:["Snap","Stop","Slip","Spin"], a:1, l:2},
    {q:"Which sentence uses a CAPITAL letter correctly?", o:["i like sport.","I like sport.","I Like Sport.","i Like sport."], a:1, l:2},
    {q:"'Foot' → PLURAL is?", o:["Foots","Feetes","Feet","Feets"], a:2, l:2},
    {q:"Which word has the 'oo' sound?", o:["Book","Cat","Run","Bed"], a:0, l:2},
    {q:"'Mouse' → PLURAL is?", o:["Mouses","Mice","Meece","Mouse"], a:1, l:2},
    {q:"What do we put at the END of a question?", o:["Full stop (.)","Comma (,)","Question mark (?)","Exclamation mark (!)"], a:2, l:2},
    {q:"Which word has the 'sh' sound?", o:["Stone","Chest","Shell","Chin"], a:2, l:2},
    {q:"What is the OPPOSITE of 'hot'?", o:["Warm","Hotter","Cold","Heat"], a:2, l:2},
    // Level 3 — grammar, antonyms, word meanings
    {q:"A sentence must start with a ___", o:["full stop","capital letter","comma","question mark"], a:1, l:3},
    {q:"What is the OPPOSITE of 'day'?", o:["Sun","Evening","Night","Moon"], a:2, l:3},
    {q:"'Run' → add '-ing' to make?", o:["Runing","Running","Runned","Runs"], a:1, l:3},
    {q:"Which word is a NAMING word (noun)?", o:["Jump","Blue","Ball","Quickly"], a:2, l:3},
    {q:"'Child' → PLURAL is?", o:["Childs","Childrens","Children","Childer"], a:2, l:3},
    {q:"A sentence that asks something ends with a ___", o:["comma","exclamation mark","full stop","question mark"], a:3, l:3},
    {q:"What does the word 'enormous' mean?", o:["Tiny","Medium","Very big","Colourful"], a:2, l:3},
    {q:"'The dog ran fast.' — what is the VERB (doing word)?", o:["dog","the","ran","fast"], a:2, l:3},
    {q:"Which of these is a SENTENCE?", o:["Big red ball","The boy kicked the ball.","Running fast outside","Happy and fun"], a:1, l:3},
  ],

  english_34: [
    // Level 1 — nouns/verbs/adjectives, simple synonyms
    {q:"Which word is a VERB (doing/action word)?", o:["Happy","Quickly","Kicked","Ball"], a:2, l:1},
    {q:"Which word is an ADJECTIVE (describing word)?", o:["Run","Fluffy","Ball","Shouted"], a:1, l:1},
    {q:"A SYNONYM for 'happy' is?", o:["Sad","Glad","Angry","Tired"], a:1, l:1},
    {q:"Which word is a NOUN?", o:["Jumped","Slowly","Stadium","Bright"], a:2, l:1},
    {q:"The ANTONYM (opposite) of 'ancient' is?", o:["Old","Modern","Broken","Large"], a:1, l:1},
    {q:"Which sentence has an ADJECTIVE?", o:["Dogs run fast.","She ate lunch.","The tall boy scored.","They played outside."], a:2, l:1},
    {q:"'Said' is an example of a ___", o:["noun","adjective","verb","adverb"], a:2, l:1},
    {q:"A synonym for 'angry' is?", o:["Calm","Sleepy","Furious","Quiet"], a:2, l:1},
    {q:"Which word is a PROPER noun?", o:["city","dog","Australia","ball"], a:2, l:1},
    // Level 2 — adverbs, prefixes/suffixes, text types
    {q:"An ADVERB describes a ___", o:["noun","verb","adjective","pronoun"], a:1, l:2},
    {q:"The prefix 'un-' means?", o:["again","before","not","between"], a:2, l:2},
    {q:"What TYPE of text is a recipe?", o:["Narrative","Persuasive","Procedure","Report"], a:2, l:2},
    {q:"'quickly' is an example of an ___", o:["noun","verb","adjective","adverb"], a:3, l:2},
    {q:"The suffix '-ful' means?", o:["without","full of","before","again"], a:1, l:2},
    {q:"A NARRATIVE text tells a ___", o:["how to do something","story","opinion","set of facts"], a:1, l:2},
    {q:"'Dis-' in 'disagree' means?", o:["again","not/opposite","before","very"], a:1, l:2},
    {q:"Which word contains a suffix?", o:["replay","helpful","unkind","unhappy"], a:1, l:2},
    {q:"What punctuation goes inside speech marks?", o:["The words someone said","A describing word","A naming word","An action word"], a:0, l:2},
    // Level 3 — figurative language, complex grammar, vocabulary
    {q:"'She ran like the wind' is a ___", o:["Metaphor","Simile","Alliteration","Hyperbole"], a:1, l:3},
    {q:"'The sun is a golden coin' is a ___", o:["Simile","Alliteration","Metaphor","Onomatopoeia"], a:2, l:3},
    {q:"'Peter Piper picked a peck' uses ___", o:["Rhyme","Alliteration","Metaphor","Simile"], a:1, l:3},
    {q:"Which sentence is in PAST tense?", o:["She runs fast.","She will run fast.","She ran fast.","She is running."], a:2, l:3},
    {q:"An ANTONYM for 'enormous' is?", o:["Large","Gigantic","Tiny","Huge"], a:2, l:3},
    {q:"A PERSUASIVE text aims to ___", o:["tell a story","explain how to","convince the reader","describe a place"], a:2, l:3},
    {q:"'Crash!' 'Boom!' are examples of ___", o:["Simile","Metaphor","Onomatopoeia","Alliteration"], a:2, l:3},
    {q:"The word 'un-break-able' has ___ morphemes.", o:["1","2","3","4"], a:2, l:3},
    {q:"Which sentence uses CORRECT punctuation?", o:["where are you going","Where are you going?","where are you going?","Where are you going"], a:1, l:3},
  ],

  english_56: [
    // Level 1 — simile/metaphor, synonyms for complex words, sentence types
    {q:"'As brave as a lion' is a ___", o:["Metaphor","Simile","Alliteration","Personification"], a:1, l:1},
    {q:"A SYNONYM for 'essential' is?", o:["Useless","Necessary","Optional","Rare"], a:1, l:1},
    {q:"Which sentence is IMPERATIVE (a command)?", o:["Is the door open?","Close the door.","The door is open.","How tall the door is!"], a:1, l:1},
    {q:"A COMPLEX sentence contains ___", o:["two independent clauses","one main clause and one dependent clause","only nouns","two verbs"], a:1, l:1},
    {q:"The ANTONYM of 'transparent' is?", o:["Clear","Bright","Opaque","Shiny"], a:2, l:1},
    {q:"'Laughter is the best medicine' is an ___", o:["Simile","Metaphor","Idiom","Alliteration"], a:2, l:1},
    {q:"Which word has a NEGATIVE prefix?", o:["replace","unnecessary","before","helpful"], a:1, l:1},
    {q:"An EXCLAMATORY sentence ends with ___", o:["full stop","question mark","comma","exclamation mark"], a:3, l:1},
    {q:"A synonym for 'exhausted' is?", o:["Energetic","Tired","Happy","Angry"], a:1, l:1},
    // Level 2 — alliteration/assonance, active/passive, clauses, vocabulary in context
    {q:"'Sally sells seashells' is an example of ___", o:["Assonance","Onomatopoeia","Alliteration","Rhyme"], a:2, l:2},
    {q:"'The ball was kicked by Tom.' — this sentence is ___", o:["Active voice","Passive voice","Present tense","Imperative"], a:1, l:2},
    {q:"A SUBORDINATE clause ___", o:["can stand alone","cannot stand alone","is always a question","contains two verbs"], a:1, l:2},
    {q:"In context: 'The athlete was elated after winning.' 'Elated' means?", o:["Exhausted","Disappointed","Very happy","Nervous"], a:2, l:2},
    {q:"'Tom kicked the ball.' — this sentence is ___", o:["Passive voice","Active voice","Interrogative","Imperative"], a:1, l:2},
    {q:"Assonance is the repetition of ___", o:["consonant sounds","vowel sounds","whole words","sentences"], a:1, l:2},
    {q:"A COMPOUND sentence joins two clauses with a ___", o:["subordinating conjunction","coordinating conjunction","semicolon only","comma only"], a:1, l:2},
    {q:"'Serendipity' means?", o:["Sadness","Making lucky discoveries by chance","Hard work","Confusion"], a:1, l:2},
    {q:"Which word is an abstract noun?", o:["Table","Running","Freedom","Quickly"], a:2, l:2},
    // Level 3 — author's purpose, tone, complex figurative language, etymology
    {q:"The ROOT word 'aqua' (Latin) means?", o:["Fire","Earth","Air","Water"], a:3, l:3},
    {q:"A text with FORMAL tone would use ___", o:["slang and abbreviations","incomplete sentences","complex vocabulary and full sentences","emojis and casual language"], a:2, l:3},
    {q:"PERSONIFICATION gives ___ human qualities.", o:["animals only","objects or abstract things","other people","verbs"], a:1, l:3},
    {q:"The Greek root 'bio' means?", o:["Water","Sun","Life","Earth"], a:2, l:3},
    {q:"Which technique is used in 'The angry storm devoured the ships'?", o:["Simile","Alliteration","Personification","Onomatopoeia"], a:2, l:3},
    {q:"An author writing to INFORM aims to ___", o:["entertain with a story","share opinions","provide facts and knowledge","persuade the reader"], a:2, l:3},
    {q:"A HYPERBOLE is ___", o:["a comparison using 'like' or 'as'","an extreme exaggeration for effect","giving objects human traits","repetition of sounds"], a:1, l:3},
    {q:"The prefix 'inter-' means?", o:["before","after","between","against"], a:2, l:3},
    {q:"Which word pair are HOMOPHONES?", o:["their / there","big / large","run / ran","fast / slow"], a:0, l:3},
  ],

  stem_f2: [
    // Level 1 — living/non-living, materials, basic instructions
    {q:"Which of these is LIVING?", o:["Rock","Cloud","Plant","Water"], a:2, l:1},
    {q:"Which material is HARD?", o:["Cotton","Water","Wood","Smoke"], a:2, l:1},
    {q:"A DOG needs ___ to stay alive.", o:["Electricity","Food and water","Petrol","Wood"], a:1, l:1},
    {q:"Which is a step in getting dressed? Put them in order — which comes FIRST?", o:["Put on shoes","Put on socks","Go outside","Tie laces"], a:1, l:1},
    {q:"Which material would be BEST to make a raincoat?", o:["Paper","Cotton","Waterproof plastic","Cardboard"], a:2, l:1},
    {q:"The sun gives us ___", o:["Rain","Light and warmth","Snow","Wind"], a:1, l:1},
    {q:"Which of these is NOT living?", o:["Dog","Tree","River","Flower"], a:2, l:1},
    {q:"To make toast, what is the CORRECT order? 1-Put bread in, 2-___, 3-Eat", o:["Eat toast","Push lever down & wait","Buy bread","Put butter on"], a:1, l:1},
    {q:"Which is ROUGH in texture?", o:["Ice","Silk","Sandpaper","Jelly"], a:2, l:1},
    // Level 2 — materials properties, animals/plants, weather
    {q:"Plants need ___ to grow.", o:["Electricity and petrol","Sunlight, water, and soil","Snow and ice","Darkness only"], a:1, l:2},
    {q:"Which animal is a MAMMAL?", o:["Eagle","Frog","Dolphin","Shark"], a:2, l:2},
    {q:"What is WEATHER?", o:["What stars look like","Conditions of the atmosphere outside","How hot the ground is","The colour of the sky only"], a:1, l:2},
    {q:"Which material is the BEST conductor of heat?", o:["Plastic","Wood","Metal","Rubber"], a:2, l:2},
    {q:"Which season has the MOST rainfall in many parts of Australia?", o:["Summer","Autumn","Winter","Spring"], a:2, l:2},
    {q:"A caterpillar changes into a ___", o:["Beetle","Butterfly","Spider","Worm"], a:1, l:2},
    {q:"Which floats in water?", o:["A rock","A coin","A rubber duck","A marble"], a:2, l:2},
    {q:"Day and night happen because Earth ___", o:["moves toward the sun","spins on its axis","changes shape","moves away from the moon"], a:1, l:2},
    {q:"Which living thing makes its OWN food from sunlight?", o:["Dog","Cat","Grass","Fish"], a:2, l:2},
    // Level 3 — seasons, simple food relationships, sequencing (algorithms)
    {q:"Australia has ___ seasons.", o:["2","3","4","5"], a:2, l:3},
    {q:"A rabbit eats grass. The rabbit is a ___", o:["producer","consumer","decomposer","predator"], a:1, l:3},
    {q:"Put in order: 1-Log in, 2-___, 3-Print. What goes in the middle?", o:["Turn off computer","Open the document","Eat lunch","Buy paper"], a:1, l:3},
    {q:"What is the CORRECT order for brushing teeth?", o:["Rinse, brush, put on toothpaste","Put on toothpaste, brush, rinse","Brush, rinse, put on toothpaste","Rinse, put on toothpaste, brush"], a:1, l:3},
    {q:"In winter, some animals HIBERNATE. This means they ___", o:["fly to warmer places","sleep through winter","eat more food","grow thicker fur"], a:1, l:3},
    {q:"Which is the correct sequence? (Algorithm for making a sandwich)", o:["Eat it, put filling in, get bread","Get bread, put filling in, eat it","Put filling in, get bread, eat it","Eat it, get bread, put filling in"], a:1, l:3},
    {q:"Grass → Rabbit → Fox. The GRASS is the ___", o:["consumer","predator","producer","decomposer"], a:2, l:3},
    {q:"A frog is an AMPHIBIAN. It can live ___", o:["only in water","only on land","in water AND on land","only in trees"], a:2, l:3},
    {q:"Which of these describes an ALGORITHM?", o:["A type of food","Step-by-step instructions to solve a problem","A kind of animal","A weather pattern"], a:1, l:3},
  ],

  stem_34: [
    // Level 1 — food chains, states of matter, push/pull
    {q:"In a food chain, the SUN's energy is first captured by?", o:["Animals","Plants","Fungi","Bacteria"], a:1, l:1},
    {q:"Ice is water in its ___ state.", o:["liquid","gas","solid","plasma"], a:2, l:1},
    {q:"Pushing a door open is an example of a ___", o:["pull force","gravity","push force","friction"], a:2, l:1},
    {q:"In the food chain: Grass → Caterpillar → Bird. The BIRD is a ___", o:["producer","herbivore","carnivore (consumer)","plant"], a:2, l:1},
    {q:"Water vapour is water in its ___ state.", o:["solid","liquid","gas","frozen"], a:2, l:1},
    {q:"Which force pulls objects toward the Earth?", o:["Friction","Magnetism","Gravity","Electricity"], a:2, l:1},
    {q:"True or False: A TRUE statement means it is ___", o:["wrong","right/correct","unknown","maybe"], a:1, l:1},
    {q:"A PRODUCER in a food chain is usually a ___", o:["herbivore","plant","carnivore","fungi"], a:1, l:1},
    {q:"When water FREEZES it turns from ___ to ___", o:["gas to solid","liquid to solid","solid to gas","solid to liquid"], a:1, l:1},
    // Level 2 — adaptations, changing states, simple algorithms
    {q:"Polar bears have white fur so they can ___", o:["attract prey","camouflage in snow","absorb more heat","swim faster"], a:1, l:2},
    {q:"When water EVAPORATES, it turns from liquid to ___", o:["solid","ice","gas","rock"], a:2, l:2},
    {q:"Which is a LOOP in an algorithm? (repeating steps)", o:["If-then","Count to 10 three times","Start","End"], a:1, l:2},
    {q:"A DESERT animal adaptation might include?", o:["Thick waterproof fur","Ability to store water and withstand heat","Webbed feet","Very large eyes for darkness"], a:1, l:2},
    {q:"FRICTION is a force that ___", o:["speeds things up","pulls things down","slows things down","pushes things sideways"], a:2, l:2},
    {q:"When you heat ice, it ___", o:["stays solid","melts into liquid","turns to gas immediately","disappears"], a:1, l:2},
    {q:"If a computer does something ONLY when a condition is true, that is called?", o:["A loop","An if-statement (conditional)","A variable","A function"], a:1, l:2},
    {q:"A fish has GILLS so it can ___", o:["see in the dark","breathe underwater","swim faster","hear better"], a:1, l:2},
    {q:"Which materials are MAGNETIC?", o:["Wood and plastic","Iron and steel","Glass and rubber","Cotton and paper"], a:1, l:2},
    // Level 3 — ecosystems, boolean logic, more complex forces
    {q:"A DECOMPOSER in an ecosystem ___", o:["makes food from sunlight","eats animals","breaks down dead material","stores water"], a:2, l:3},
    {q:"TRUE AND TRUE = ?", o:["FALSE","TRUE","MAYBE","ERROR"], a:1, l:3},
    {q:"TRUE AND FALSE = ?", o:["TRUE","FALSE","MAYBE","ERROR"], a:1, l:3},
    {q:"A simple electrical circuit needs ___", o:["water and wire","a battery, wire, and a bulb","only a battery","only a bulb"], a:1, l:3},
    {q:"When testing a design, we change ___ variable at a time.", o:["as many as possible","zero","one","two"], a:2, l:3},
    {q:"NOT TRUE = ?", o:["TRUE","FALSE","MAYBE","ERROR"], a:1, l:3},
    {q:"Which force acts between two MAGNETS?", o:["Gravity","Friction","Magnetic force","Air resistance"], a:2, l:3},
    {q:"An ecosystem includes both ___ and ___ parts.", o:["wet and dry","living (biotic) and non-living (abiotic)","plant and animal","large and small"], a:1, l:3},
    {q:"In coding, a VARIABLE is used to ___", o:["stop a program","store information","create a loop","turn on a screen"], a:1, l:3},
  ],

  stem_56: [
    // Level 1 — energy types, solar system, simple circuits
    {q:"A ball held high has ___ energy.", o:["Kinetic","Chemical","Potential","Electrical"], a:2, l:1},
    {q:"What is the CORRECT order of planets from the sun? (first three)", o:["Earth, Venus, Mercury","Mercury, Venus, Earth","Venus, Earth, Mercury","Earth, Mercury, Venus"], a:1, l:1},
    {q:"A moving car has ___ energy.", o:["Potential","Kinetic","Chemical","Nuclear"], a:1, l:1},
    {q:"In a circuit, the SWITCH is used to ___", o:["store electricity","control the flow of electricity","make electricity","measure electricity"], a:1, l:1},
    {q:"Which planet is LARGEST in our solar system?", o:["Saturn","Neptune","Earth","Jupiter"], a:3, l:1},
    {q:"Food gives our body ___ energy.", o:["Electrical","Kinetic","Chemical","Light"], a:2, l:1},
    {q:"The Earth takes ___ to orbit the sun.", o:["1 day","1 month","1 year","10 years"], a:2, l:1},
    {q:"An OPEN circuit means electricity ___", o:["flows freely","is stored","cannot flow","creates heat"], a:2, l:1},
    {q:"Burning fuel is an example of ___ energy being released.", o:["Electrical","Potential","Chemical","Kinetic"], a:2, l:1},
    // Level 2 — ecosystems producers/consumers/decomposers, variables in code, genetics basics
    {q:"Which organism is a DECOMPOSER?", o:["Grass","Eagle","Mushroom (fungi)","Snake"], a:2, l:2},
    {q:"In code: x = 5, then x = x + 3. What is x now?", o:["5","3","8","15"], a:2, l:2},
    {q:"Which of the following is an example of INHERITED trait?", o:["Speaking French","Eye colour","Knowing how to ride a bike","Having short hair"], a:1, l:2},
    {q:"A CONSUMER that ONLY eats plants is called a ___", o:["carnivore","herbivore","omnivore","decomposer"], a:1, l:2},
    {q:"In code: if score > 10: print('Win'). When does 'Win' print?", o:["Always","When score equals 10","When score is more than 10","Never"], a:2, l:2},
    {q:"DNA contains the ___ for building living things.", o:["water","instructions (genetic code)","energy","protein only"], a:1, l:2},
    {q:"In a food web, removing ONE species can affect ___", o:["nothing else","only the species next to it","many other species","only plants"], a:2, l:2},
    {q:"In code, a LOOP runs a set of instructions ___", o:["once only","randomly","a set number of times or until a condition is met","never again"], a:2, l:2},
    {q:"Humans are OMNIVORES because we eat ___", o:["only plants","only animals","both plants and animals","only fungi"], a:2, l:2},
    // Level 3 — water cycle, rock cycle, if-else logic, engineering design
    {q:"In the WATER CYCLE, evaporation changes water from ___", o:["gas to liquid","solid to liquid","liquid to gas","solid to gas"], a:2, l:3},
    {q:"In code: if x > 5: print('Big') else: print('Small'). x=5. What prints?", o:["Big","Small","Nothing","Error"], a:1, l:3},
    {q:"Which rock type forms from cooled lava/magma?", o:["Sedimentary","Metamorphic","Igneous","Fossil"], a:2, l:3},
    {q:"The ENGINEERING DESIGN PROCESS starts with ___", o:["Building the solution","Identifying the problem","Testing","Evaluating results"], a:1, l:3},
    {q:"In the water cycle, CONDENSATION turns water vapour back to ___", o:["ice","liquid water","steam","soil"], a:1, l:3},
    {q:"An IF-ELSE statement means ___", o:["do both options always","do one thing if true, another if false","repeat until done","stop the program"], a:1, l:3},
    {q:"Which is a RENEWABLE energy source?", o:["Coal","Oil","Solar power","Natural gas"], a:2, l:3},
    {q:"In engineering, a PROTOTYPE is ___", o:["the final product","an early test model","a computer program","a design rule"], a:1, l:3},
    {q:"METAMORPHIC rocks form when rocks are changed by ___", o:["water erosion","heat and pressure","cooling from lava","wind erosion"], a:1, l:3},
  ],
};
